// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanBarberAPI.Data;

#nullable disable

namespace UrbanBarberAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126221607_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrbanBarberAPI.Models.Barbero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitasAtendidas")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("Id");

                    b.ToTable("Barberos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CitasAtendidas = 0,
                            Disponible = true,
                            Especialidad = "Cortes Tradicionales",
                            Experiencia = "10 años",
                            Imagen = "",
                            Nombre = "Ricardo 'El Clásico'",
                            Rating = 4.9m
                        },
                        new
                        {
                            Id = 2,
                            CitasAtendidas = 0,
                            Disponible = true,
                            Especialidad = "Diseños y Fade Modernos",
                            Experiencia = "8 años",
                            Imagen = "",
                            Nombre = "Rafael 'El Diseñador'",
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 3,
                            CitasAtendidas = 0,
                            Disponible = true,
                            Especialidad = "Afeitado con Navaja y Patillas",
                            Experiencia = "12 años",
                            Imagen = "",
                            Nombre = "Juan 'El Lápiz'",
                            Rating = 5.0m
                        });
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransaccionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Popularidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Corte clásico y limpio",
                            Disponible = true,
                            Duracion = 45,
                            Nombre = "Corte Sencillo",
                            Popularidad = 0,
                            Precio = 25000m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Corte preciso y diseño de cejas",
                            Disponible = true,
                            Duracion = 50,
                            Nombre = "Corte + Cejas",
                            Popularidad = 0,
                            Precio = 25000m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Servicio completo",
                            Disponible = true,
                            Duracion = 60,
                            Nombre = "Tratamiento Corte Premium (Cejas + Perfilado de Barba)",
                            Popularidad = 0,
                            Precio = 40000m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Definición exacta",
                            Disponible = true,
                            Duracion = 20,
                            Nombre = "Perfilado de Barba",
                            Popularidad = 0,
                            Precio = 15000m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Corte moderno con color",
                            Disponible = true,
                            Duracion = 90,
                            Nombre = "Corte + Tinturado de Cabello",
                            Popularidad = 0,
                            Precio = 35000m
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Corte con mascarilla facial",
                            Disponible = true,
                            Duracion = 60,
                            Nombre = "Corte + Mascarilla",
                            Popularidad = 0,
                            Precio = 35000m
                        });
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Sistema",
                            Celular = "3001234567",
                            Correo = "admin@urbanbarber.com",
                            FechaRegistro = new DateTime(2025, 11, 26, 22, 16, 7, 458, DateTimeKind.Utc).AddTicks(4594),
                            Nombre = "Administrador",
                            PasswordHash = "$2a$11$rG8pZ4YX3VkL5qKz.mXlvuJXZxvYvN8WqH5L1fZQ2xGKmEYvXqxCi",
                            Rol = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Cita", b =>
                {
                    b.HasOne("UrbanBarberAPI.Models.Barbero", "Barbero")
                        .WithMany("Citas")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanBarberAPI.Models.Servicio", "Servicio")
                        .WithMany("Citas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanBarberAPI.Models.Usuario", "Usuario")
                        .WithMany("Citas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Servicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Pago", b =>
                {
                    b.HasOne("UrbanBarberAPI.Models.Cita", "Cita")
                        .WithOne("Pago")
                        .HasForeignKey("UrbanBarberAPI.Models.Pago", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Barbero", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Cita", b =>
                {
                    b.Navigation("Pago")
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Servicio", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("UrbanBarberAPI.Models.Usuario", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
